INSERT INTO dbsec.sdb_configure VALUES ('MIIBzwIBADGCAWswggFnAgEAME8wSjELMAkGA1UEBhMCS1IxDTALBgNVBAoMBEtJQ0ExFTATBgNVBAsMDEFjY3JlZGl0ZWRDQTEVMBMGA1UEAwwMc2lnbkdBVEUgQ0E0AgEUMA0GCSqGSIb3DQEBBzAABIIBADoYuFfnVniBB8MXqQYJtGjooa/u0YmYkPERt8Ri9hjHgQ4n4O4fzPCgnKB5UvlO8Qwzr8/lnTDcNpXfMv7I77iew+EWATl3JNAJSvROqOKUlFF35kngy0RlbqFLV8SOFFtlCtzcdvzK9GrS9GZbNYnEkVcIqn13lF4M7i2b/ZjfOfEugJmYSJUaBQpQdtHGZzJucM+hZXn1q60x8zF/9Y7r9/wBe22VYtwpa4G520gtRxbECr8NoLD5DgfYoJfAadk+mujEJ/AlK9SG9B2DG2FNx/cTKn+5z+vPpfYWlteeN/ogPwZxhJwe/Q4NKiFSIMUeZtwsjhE1inS6WQbtjd0wWwYJKoZIhvcNAQcBMBwGCCqDGoyaRAEEBBBtUPM81AEezN/FpoNnPslDgDB0iF3fg4/Ctdd3uiG3+xu4YI46i2KcjEIZPMzztBp3sfKKQvgH9fdhkKjL4vp3e28=', '2020-10-14', 'F', 5, 10, 1, 1, 'T', 5, NULL, NULL, NULL, NULL, 80, 'F', 'F', '30', NULL, NULL, NULL, NULL, NULL, '1', 'F', 'localhost', '0', 'securedb');
INSERT INTO dbsec.sdb_admin VALUES (1, 'root', 'root', '5BXusnq07/pz/6Q29WvNndMCCmBlqa5c4UYNtD/AkMc=', 'tttt', '', 'form-based', 0, 'T', NULL, NULL);
INSERT INTO dbsec.sdb_agent VALUES (1, 'DEMO', 'LINUX', 'vj0z+bx/X29BNY5hKSQR/g==', 'PostgreSQL', '9.5', 'z8erGPwi91lTfyT5Z9x6tQ==', 'Zm0M1xtxOJ0Ug7dBr/+Wug==', 'g0zYZo5ExUyoocpaWhc4Yg==', 'fCxK/kKrsvVJhi0f5fvqDg==', 'fCxK/kKrsvVJhi0f5fvqDg==', 'F$F$F$F$F$F$F$F$', 0, 2, '9hmWxz3iYOAHQ1uCLvFgNA==', NULL, NULL, 'T', 1, NULL, NULL, NULL, NULL, 'D', 'F', 80, 'T', 'F', '', 'F', 'F', NULL);
INSERT INTO dbsec.sdb_obj VALUES (1, 1, 'mkey', 'TAB', 'securedb', '', 'dbsec', 2, '1', NULL, NULL, NULL, NULL, 2, NULL, 'N', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dbsec.sdb_obj VALUES (2, 1, 'aria128', 'COL', NULL, NULL, NULL, NULL, NULL, 'character varying', '', 'D', NULL, 3, -1, NULL, '', NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dbsec.sdb_obj VALUES (3, 1, 'aria256', 'COL', NULL, NULL, NULL, NULL, NULL, 'character varying', '', 'D', NULL, 4, -1, NULL, '', NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dbsec.sdb_obj VALUES (4, 1, 'aes128', 'COL', NULL, NULL, NULL, NULL, NULL, 'character varying', '', 'D', NULL, 5, -1, NULL, '', NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dbsec.sdb_obj VALUES (5, 1, 'aes256', 'COL', NULL, NULL, NULL, NULL, NULL, 'character varying', '', 'D', NULL, 6, -1, NULL, '', NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dbsec.sdb_obj VALUES (6, 1, 'sha256', 'COL', NULL, NULL, NULL, NULL, NULL, 'character varying', '', 'D', NULL, 7, -1, NULL, '', NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dbsec.sdb_obj VALUES (7, 1, 'sha512', 'COL', NULL, NULL, NULL, NULL, NULL, 'character varying', '', 'D', NULL, 8, -1, NULL, '', NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO dbsec.sdb_colcons VALUES (1, 2, ' ', '');
INSERT INTO dbsec.sdb_colcons VALUES (2, 3, ' ', '');
INSERT INTO dbsec.sdb_colcons VALUES (3, 4, ' ', '');
INSERT INTO dbsec.sdb_colcons VALUES (4, 5, ' ', '');
INSERT INTO dbsec.sdb_colcons VALUES (5, 6, ' ', '');
INSERT INTO dbsec.sdb_colcons VALUES (6, 7, ' ', '');
INSERT INTO dbsec.sdb_key VALUES (1, 1, 'G-KEY', 'SEED', 'Eb+WEymtlHDkW4OWCaA45cm98sqWdlt024f4DuK+Zk6uhh8mwHm9TiL7UnsKPHxN', 'F', 'WmYzQzT0rG1BHEi4qQE/vsCmxvk6tc3N2cqTo8QxV5w=', NULL, NULL, NULL);
INSERT INTO dbsec.sdb_key VALUES (2, 1, 'T-KEY', 'ARIA', 'kX17yrXRxGlFjH13tDRG/4frm0NpUsKxfVVrUtNTXjw=', 'F', 'jIF8f2f1zCmbL+XbYF8gwg/9UZmDna79nzlf3Y5gKp4=', NULL, NULL, NULL);
INSERT INTO dbsec.sdb_key VALUES (3, 1, 'U-KEY', 'ARIA', 'I3IK1CXFmv4y9LuY2ktF5mnATszr3JYflLRlx7J+s9Q=', 'F', 'tpAGz7kKThFZyVnpSSZ3h/bhz4wle6kmCYXwaUsxcrw=', NULL, NULL, NULL);
INSERT INTO dbsec.sdb_key VALUES (4, 1, 'U-KEY', 'ARIA256', 'k7iCC4IvTlZF8w8b8l+4NFouopNSczRzjreSkj+L+3A=', 'F', 'RfhEy4KxI5ExBfj0szsAtHKQC1G11qdAYQhJOAFU72g=', NULL, NULL, NULL);
INSERT INTO dbsec.sdb_key VALUES (5, 1, 'U-KEY', 'AES128', 'VDAt6any5O3KvA0SihVnSxkR6OSSR6/F2pbEZ3KsYj0=', 'F', 'iXN2Z/Phmiqd7G3Ae7OL1op1uSsBIwuddfC+dl1iwTk=', NULL, NULL, NULL);
INSERT INTO dbsec.sdb_key VALUES (6, 1, 'U-KEY', 'AES256', 'Oj1VmZ4QEGT3HL+wcLxLBFG/ATe1z4Fp5R2SOcCzPjw=', 'F', 'EXS48YDQ+jHn4xfchJY1BRStqsOVZs5ssu7f5Ev+lJU=', NULL, NULL, NULL);
INSERT INTO dbsec.sdb_key VALUES (7, 1, 'U-KEY', 'SHA256', 'w6NoeTMdOPia4N8zQKO79wcyLMWB6YdVONtXw+IJ04o=', 'F', '1YDSoKHpdyPvxNDOhBP5/gZtfehBbLqmB43dDqh2aRs=', NULL, NULL, NULL);
INSERT INTO dbsec.sdb_key VALUES (8, 1, 'U-KEY', 'SHA512', '5WolbZnEKsww4fje1U217gk48gBKAFXLsm1943pZv/I=', 'F', 'YZOqAtJRF74BxIH2A9khGRLPgP34Rvt406ABU6uxEcM=', NULL, NULL, NULL);
INSERT INTO dbsec.sdb_user VALUES (1, 1, 'dbsec', NULL, '2020-10-14', 'U', NULL, '', '', ',,', '', NULL, 'UxkcnlhH245w7E1VXS/u6hh9n+RW4RmyMuTz45ok0EE=', 'F');
INSERT INTO dbsec.sdb_tabcol VALUES (1, 2, 1);
INSERT INTO dbsec.sdb_tabcol VALUES (1, 3, 1);
INSERT INTO dbsec.sdb_tabcol VALUES (1, 4, 1);
INSERT INTO dbsec.sdb_tabcol VALUES (1, 5, 1);
INSERT INTO dbsec.sdb_tabcol VALUES (1, 6, 1);
INSERT INTO dbsec.sdb_tabcol VALUES (1, 7, 1);
